# Generated by Django 2.2.5 on 2022-04-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, help_text='one word for title alias.', max_length=10, verbose_name='DESCRIPTION'),
        ),
    ]
