# Generated by Django 2.2.5 on 2022-04-18 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('modify_dt',), 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
    ]
