# Generated by Django 2.2.5 on 2022-04-25 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='describtion',
            new_name='description',
        ),
    ]
