# Generated by Django 2.2.5 on 2022-04-26 07:21

from django.db import migrations
import photo.fields


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20220425_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image',
            field=photo.fields.ThumbnailImageField(default='', upload_to='photo/%Y/%m'),
        ),
    ]
